CREATE TABLE PROVINCIA
(
   PCODIGO varchar(5),
   NOMBRE varchar(40) NOT NULL,
   CONSTRAINT PK_PROVINCIA PRIMARY KEY (PCODIGO)
);

CREATE TABLE SUMINISTRADOR
(
   SNOMBRE varchar(10),
   PAIS varchar(6),
   STOCK decimal(10,0), 
   CONSTRAINT PK_SUMINISTRADOR PRIMARY KEY (SNOMBRE,PAIS),
   CONSTRAINT CK_STOCK_SUMINISTRADOR CHECK(STOCK>=0)
);

CREATE TABLE TRANSPORTISTA
(
   TNOMBRE varchar(30),
   MATRICULA varchar(8),
   HORASCONDUCIDAS decimal(10,0),
   CONSTRAINT PK_TRANSPORTISTA PRIMARY KEY (TNOMBRE,MATRICULA),
   CONSTRAINT CH_HORAS_TRANSPORTISTA CHECK(HORASCONDUCIDAS>=0)
);

CREATE TABLE COMPANIA
(
   CNOMBRE varchar(10),
   CAPITALSOCIAL decimal(2,0),
   CONSTRAINT PK_COMPANIA PRIMARY KEY (CNOMBRE),
   CONSTRAINT CK_CAPITAL_COMPANIA CHECK(CAPITALSOCIAL>=0)
);

CREATE TABLE ESTACION
(
   ENOMBRE varchar(15),
   TRANSFORMADORES decimal(3,0) NOT NULL,
   CONSTRAINT PK_ESTACION PRIMARY KEY (ENOMBRE),
   CONSTRAINT CK_TRANSFORMADORES CHECK(TRANSFORMADORES>=0)
);

CREATE TABLE PRODUCTOR
(
   PNOMBRE varchar(40),
   PRODMEDIA decimal(10,2) NOT NULL,
   PRODMAXIMA decimal(10,2) NOT NULL,
   FECHA date NOT NULL,
   CONSTRAINT PK_PRODUCTOR PRIMARY KEY (PNOMBRE),
   CONSTRAINT CK_PRODMEDIA_PROD CHECK(PRODMEDIA>=0),
   CONSTRAINT CK_PRODMAXIMA_PROD CHECK(PRODMAXIMA>=0)
);

CREATE TABLE ZONA
(
   ZCODIGO varchar(6),
   CONSUMOMEDIO decimal(9,2) NOT NULL,
   CONSINSTITUCIONES decimal(9,2) NOT NULL,
   CONSPARTICULARES decimal(9,2) NOT NULL,
   CONSEMPRESAS decimal(9,2) NOT NULL,
   PCODIGO varchar(5) NOT NULL,
   CONSTRAINT PK_ZONA PRIMARY KEY (ZCODIGO),
   CONSTRAINT FK_ZONA_PROVINCIA FOREIGN KEY (PCODIGO) REFERENCES PROVINCIA (PCODIGO),
   CONSTRAINT CK_CONSMEDIO CHECK(CONSUMOMEDIO>=0),
   CONSTRAINT CK_CONSINSTI CHECK(CONSINSTITUCIONES>=0),
   CONSTRAINT CK_CONSPARTI CHECK(CONSPARTICULARES>=0),
   CONSTRAINT CK_CONSEMPRE CHECK(CONSEMPRESAS>=0)
);

CREATE TABLE HIDROELECTRICA
(
   PNOMBRE varchar(40),
   OCUPACION decimal(10,0) NOT NULL,
   CAPMAXIMA decimal(10,0) NOT NULL,
   NUMTURBINAS decimal(2,0) NOT NULL,
   CONSTRAINT PK_HIDROELECTRICA PRIMARY KEY (PNOMBRE),
   CONSTRAINT FK_HIDROELECTRICA_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE),
   CONSTRAINT CK_OCUPACION CHECK(OCUPACION>=0),
   CONSTRAINT CK_CAPMAXIMA CHECK(CAPMAXIMA>=0),
   CONSTRAINT CK_NUMTURBINAS CHECK(NUMTURBINAS>=0)
);

CREATE TABLE NUCLEAR
(
   PNOMBRE varchar(40),
   NUMREACTORES decimal(10,0) NOT NULL,
   PLUTONIO decimal(6,0) NOT NULL,
   RESIDUOS decimal(6,0) NOT NULL,
   CONSTRAINT PK_NUCLEAR PRIMARY KEY (PNOMBRE),
   CONSTRAINT FK_NUCLEAR_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE),
   CONSTRAINT CK_NUMREACTORES CHECK(NUMREACTORES>=0),
   CONSTRAINT CK_PLUTONIO CHECK(PLUTONIO>=0),
   CONSTRAINT CK_RESIDUOS CHECK(RESIDUOS>=0)
);

CREATE TABLE SOLAR
(
   PNOMBRE varchar(40),
   PANELES decimal(6,0) NOT NULL,
   HORASSOL decimal(8,2) NOT NULL,
   TIPO varchar(1) NOT NULL,
   CONSTRAINT PK_SOLAR PRIMARY KEY (PNOMBRE),
   CONSTRAINT FK_SOLAR_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE),
   CONSTRAINT CK_PANELES CHECK(PANELES>=0),
   CONSTRAINT CK_HORASSOL CHECK(HORASSOL>=0)
);

CREATE TABLE TERMICA
(
   PNOMBRE varchar(40),
   HORNOS decimal(2,0) NOT NULL,
   CARBON decimal(6,0) NOT NULL,
   GASES decimal(6,0) NOT NULL,
   CONSTRAINT PK_TERMICA PRIMARY KEY (PNOMBRE),
   CONSTRAINT FK_TERMICA_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE),
   CONSTRAINT CK_HORNOS CHECK(HORNOS>=0),
   CONSTRAINT CK_CARBON CHECK(CARBON>=0),
   CONSTRAINT CK_GASES CHECK(GASES>=0)
);

CREATE TABLE RED_DISTRIBUCION
(
   NUMRED decimal(3,0),
   ENOMBRE varchar(15) NOT NULL,
   LONGITUDMAXIMA decimal(10,2),
   CONSTRAINT PK_RED_DISTRIBUCION PRIMARY KEY (NUMRED),
   CONSTRAINT FK_RED_DISTRIBUCION_ESTACION FOREIGN KEY (ENOMBRE) REFERENCES ESTACION (ENOMBRE),
   CONSTRAINT CK_LONGITUDMAX CHECK(LONGITUDMAXIMA>=0)
);


CREATE TABLE ENTREGA
(
   ENOMBRE varchar(15),
   PNOMBRE varchar(40),
   CANTIDAD decimal(6,0) NOT NULL,
   FECHA date NOT NULL,
   CONSTRAINT PK_ENTREGA PRIMARY KEY (PNOMBRE,ENOMBRE),
   CONSTRAINT FK_ENTREGA_ESTACION FOREIGN KEY (ENOMBRE) REFERENCES ESTACION (ENOMBRE),
   CONSTRAINT FK_ENTREGA_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE),
   CONSTRAINT CK_CANTIDAD_ENTREGA CHECK(CANTIDAD>=0)
);

CREATE TABLE COMPRA
(
   PNOMBRE varchar(40),
   SNOMBRE varchar(10),
   PAIS varchar(6),
   TNOMBRE varchar(30),
   MATRICULA varchar(8),
   CANTIDAD decimal(10,2) NOT NULL,
   CONSTRAINT PK_COMPRA PRIMARY KEY (TNOMBRE,MATRICULA,PNOMBRE,SNOMBRE,PAIS),
   CONSTRAINT FK_COMPRA_TRANSPORTISTA FOREIGN KEY (TNOMBRE,MATRICULA) REFERENCES TRANSPORTISTA (TNOMBRE,MATRICULA),
   CONSTRAINT FK_COMPRA_NUCLEAR FOREIGN KEY (PNOMBRE) REFERENCES NUCLEAR (PNOMBRE),
   CONSTRAINT FK_COMPRA_SUMINISTRADOR FOREIGN KEY (SNOMBRE,PAIS) REFERENCES SUMINISTRADOR (SNOMBRE,PAIS),
   CONSTRAINT CK_CANTIDAD_COMPRA CHECK(CANTIDAD>=0)	
);


CREATE TABLE PERTENECE
(
   CNOMBRE varchar(10),
   NUMRED decimal(3,0),
   NUMACCIONES decimal (9,0),
   CONSTRAINT PK_PERTENECE PRIMARY KEY (CNOMBRE,NUMRED),
   CONSTRAINT FK_PERTENECE_RED_DISTRIBUCION FOREIGN KEY (NUMRED) REFERENCES RED_DISTRIBUCION (NUMRED),
   CONSTRAINT FK_PERTENECE_COMPANIA FOREIGN KEY (CNOMBRE) REFERENCES COMPANIA (CNOMBRE),
   CONSTRAINT CK_NUMACCIONES CHECK(NUMACCIONES>=0)
);

CREATE TABLE ENVIA_ENERGIA
(
   NUMRED_ENVIA decimal(3,0),
   NUMRED_RECIBE decimal(3,0),
   VOLUMEN decimal(6,0) NOT NULL,
   CONSTRAINT PK_ENVIA_ENERGIA PRIMARY KEY (NUMRED_ENVIA,NUMRED_RECIBE),   
   CONSTRAINT FK_ENVIA_ENERGIA_RD_ENVIA FOREIGN KEY (NUMRED_ENVIA) REFERENCES RED_DISTRIBUCION (NUMRED),
   CONSTRAINT FK_ENVIA_ENERGIA_RD_RECIBE FOREIGN KEY (NUMRED_RECIBE) REFERENCES RED_DISTRIBUCION (NUMRED),
   CONSTRAINT CK_VOLUMEN_ENVIA_ENERGIA CHECK(VOLUMEN>=0)
);

CREATE TABLE LINEA
(
   NUMRED decimal(3,0),
   NLINEA decimal(2,0),
   LONGITUD decimal(10,2) NOT NULL,
   CONSTRAINT PK_LINEA PRIMARY KEY (NUMRED,NLINEA),
   CONSTRAINT FK_LINEA_RED_DISTRIBUCION FOREIGN KEY (NUMRED) REFERENCES RED_DISTRIBUCION (NUMRED),
   CONSTRAINT CK_LONGITUD CHECK(LONGITUD>=0)   
);

CREATE TABLE SUBESTACION
(
   NSUBESTACION varchar(3),
   NUMRED decimal(3,0) NOT NULL,
   NLINEA decimal(2,0) NOT NULL,
   CAPACIDAD decimal(9,0),
   CONSTRAINT PK_SUBESTACION PRIMARY KEY (NSUBESTACION),
   CONSTRAINT FK_SUBESTACION_LINEA FOREIGN KEY (NUMRED,NLINEA) REFERENCES LINEA (NUMRED,NLINEA),
   CONSTRAINT CK_SUBESTACION_CAPACIDAD CHECK(CAPACIDAD>=0)
);

CREATE TABLE DISTRIBUYE
(
   NSUBESTACION varchar(3),
   ZCODIGO varchar(6),
   CANTIDAD decimal(6,0) NOT NULL,
   FECHA date NOT NULL,
   CONSTRAINT PK_DISTRIBUYE PRIMARY KEY (ZCODIGO,NSUBESTACION),
   CONSTRAINT FK_DISTRIBUYE_SUBESTACION FOREIGN KEY (NSUBESTACION) REFERENCES SUBESTACION (NSUBESTACION),
   CONSTRAINT FK_DISTRIBUYE_ZONA FOREIGN KEY (ZCODIGO) REFERENCES ZONA (ZCODIGO),
   CONSTRAINT CK_CANTIDAD_DISTRIBUYE CHECK(CANTIDAD>=0)
);